recent fixes

diff --git a/roles/init-ansible_user/tasks/raw-sudo.yml b/roles/init-ansible_user/tasks/raw-sudo.yml
--- a/roles/init-ansible_user/tasks/raw-sudo.yml
+++ b/roles/init-ansible_user/tasks/raw-sudo.yml
@@ -8,13 +8,15 @@
 
 
 # note: the commands are ran as a single command line. Keep a ';' at the end of each line
+# update/makecache are required as the package cache can be not yet generated
 - name: Init | Bootstrap - install sudo (debian + redhat)
   raw: >
     export SUDO_GRP=sudo;
     if [ ! -s /usr/bin/sudo ]; then
       echo 'sudo required';
-      if   [ -x /usr/bin/apt ]; then /usr/bin/apt --quiet -y install sudo;
-      elif [ -x /usr/bin/yum ]; then /usr/bin/yum install -y sudo; export SUDO_GRP=wheel;
+      if   [ -x /usr/bin/apt ]; then /usr/bin/apt update --quiet; /usr/bin/apt --quiet -y install sudo;
+      elif [ -x /usr/bin/yum ]; then /usr/bin/yum makecache --quiet; /usr/bin/yum install --quiet -y sudo; export SUDO_GRP=wheel;
+      else echo 'The package manager is not found or unmanaged'; exit 1;
       fi;
       sleep 3;
     fi;
@@ -22,7 +24,7 @@
     usermod --append --groups $SUDO_GRP  {{ ansible_user }};
   register: bootstrap_sudo
   changed_when: bootstrap_sudo.stdout is search('sudo required')
-  when: system_with_sudo.rc != 0
+  when: system_with_sudo is changed
   become: yes
   become_method: "su"
 
